### ISSUE TITLE
Add the contextPath back to application.yml !

### ISSUE THREAD

**Issue by aadrian** [grails-profiles/web#10]
Please add the contextPath back to the `application.yml` !
```yml
---
server:
    contextPath: '/@grails.codegen.defaultPackage@' 
```

Thank you.
