### ISSUE TITLE
Scriptlet in GSP doesn't escape HTML text

### ISSUE THREAD

**Issue by nobeans** [grails-profiles/web#16]
`<%= htmlText %>` doesn't escape HTML text.

In a GSP file:
```
${"<font color='red'>EXPRESSION</font>"}
<%= "<font color='red'>SCRIPTLET</font>" %>
```
Result:
<img width="324" alt="2019-02-28 20 18 05" src="https://user-images.githubusercontent.com/18579/53562929-01a16b80-3b96-11e9-8720-d70a8193b7e3.png">

It's because the configuration value in application.yml is wrong.
The correct key is `scriptlet`, but the current value is `scriptlets`.

https://github.com/grails-profiles/web/blob/master/skeleton/grails-app/conf/application.yml
```
grails:
  #...
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html    # This is wrong. The correct key is `scriptlet`
                taglib: none
                staticparts: none
```
